## YAML Template.
---
name: ResetWarningChat
main: com.garnica1999.resetwarningchat.ResetWarningChat
version: 1.0
commands:
   rw:
      description: Este es un comando de ejemplo.
      usage: /<command> [message] [timereset]
      permission: resetwarningchat.rw
      permission-message: Usted no tiene <permiso>